apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-dev-test:SNAPSHOT-23
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: go-dev-test:SNAPSHOT-23
  template:
    metadata:
      labels:
        app: go-dev-test:SNAPSHOT-23
    spec:
      containers:
      - image: wahaoo/go-dev-test:SNAPSHOT-23
        name: go-dev-test:SNAPSHOT-23
        ports:
        - containerPort: 9001