apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-dev-test
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: go-dev-test
  template:
    metadata:
      labels:
        app: go-dev-test
    spec:
      containers:
      - image: wahaoo/go-dev-test:SNAPSHOT-26
        name: go-dev-test
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_APPMODE
          value: release
        resources:
          limits:
           cpu: 100m
           memory: 0.1Gi
